
convnext_tiny:
  optimizer:
    type: 'AdamW'
    lr: 2.0e-3  
    weight_decay: 0.05
    betas: [0.9, 0.999]
    eps: 1.0e-8
  scheduler:
    type: 'CosineAnnealingLR'
    T_max: 100
    eta_min: 1.0e-6
    warmup_epochs: 5
    warmup_start_lr: 1.0e-6

convnext_small:
  optimizer:
    type: 'AdamW' 
    lr: 1.5e-3  
    weight_decay: 0.05
    betas: [0.9, 0.999]
    eps: 1.0e-8
  scheduler:
    type: 'CosineAnnealingLR'
    T_max: 100
    eta_min: 1.0e-6
    warmup_epochs: 5
    warmup_start_lr: 1.0e-6

convnext_base:
  optimizer:
    type: 'AdamW'
    lr: 0.0005  
    weight_decay: 0.05
    betas: [0.9, 0.999]
    eps: 1.0e-8
  scheduler:
    type: 'CosineAnnealingLR'
    T_max: 100  
    eta_min: 1.0e-6  
    warmup_epochs: 5  
    warmup_start_lr: 1.0e-6  

convnext_large:
  optimizer:
    type: 'AdamW'
    lr: 5.0e-4  
    weight_decay: 0.05
    betas: [0.9, 0.999]
    eps: 1.0e-8
  scheduler:
    type: 'CosineAnnealingLR'
    T_max: 100
    eta_min: 1.0e-6
    warmup_epochs: 5
    warmup_start_lr: 1.0e-6

convnext_xlarge:
  optimizer:
    type: 'AdamW'
    lr: 2.5e-4  
    weight_decay: 0.05
    betas: [0.9, 0.999]
    eps: 1.0e-8
  scheduler:
    type: 'CosineAnnealingLR'
    T_max: 100
    eta_min: 1.0e-6
    warmup_epochs: 5
    warmup_start_lr: 1.0e-6