
mobilenetv3_small:
  optimizer:
    type: AdamW
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.05
  scheduler:
    type: CosineAnnealingLR
    T_max: 100
    eta_min: 1e-6
    warmup_epochs: 5
    warmup_start_lr: 1e-6

mobilenetv3_large:
  optimizer:
    type: RMSprop
    lr: 0.0004
    momentum: 0.9
    weight_decay: 1e-4
    eps: 0.001
  scheduler:
    type: CosineAnnealingLR
    T_max: 100
    eta_min: 1e-7
    warmup_epochs: 5
    warmup_start_lr: 1e-6