
swin_tiny: &swin_default
  optimizer:
    type: AdamW
    lr: 0.001  
    betas: [0.9, 0.999]
    weight_decay: 0.05
  scheduler:
    type: CosineAnnealingLR
    T_max: 150
    eta_min: 0.0000075  
    warmup_epochs: 10
    warmup_start_lr: 0.00003  

swin_small:
  <<: *swin_default
  optimizer:
    type: AdamW
    lr: 0.00012  
    betas: [0.9, 0.999]
    weight_decay: 0.05
  scheduler:
    type: CosineAnnealingLR
    T_max: 100
    eta_min: 0.000006  
    warmup_epochs: 10
    warmup_start_lr: 0.000024  

swin_base:  
  optimizer:
    type: AdamW
    lr: 0.0003  
    betas: [0.9, 0.999]
    weight_decay: 0.1  
  scheduler:
    type: CosineAnnealingLR
    T_max: 100
    eta_min: 0.000003  
    warmup_epochs: 10  
    warmup_start_lr: 0.000006  
  gradient_clip:
    max_norm: 5.0
    norm_type: 2

swin_large:
  optimizer:
    type: AdamW
    lr: 0.00005  
    betas: [0.9, 0.999]
    weight_decay: 0.08  
  scheduler:
    type: CosineAnnealingLR
    T_max: 100
    eta_min: 0.000005  
    warmup_epochs: 8  
    warmup_start_lr: 0.00001  