
vit_tiny:
  optimizer:
    type: AdamW
    lr: 0.0005
    betas: [0.9, 0.999]
    weight_decay: 0.03
  scheduler:
    type: WarmupCosineSchedule
    warmup_steps: 346
    t_total: 17300
    cycles: 0.3

vit_base:
  optimizer:
    type: AdamW
    lr: 0.0002
    betas: [0.9, 0.999]
    weight_decay: 0.05
  scheduler:
    type: CosineAnnealingLR
    T_max: 100
    eta_min: 0.00001  
    warmup_epochs: 10
    warmup_start_lr: 0.00004

vit_small:
  optimizer:
    type: AdamW
    lr: 0.0003
    betas: [0.9, 0.999]
    weight_decay: 0.05
  scheduler:
    type: WarmupCosineSchedule
    warmup_steps: 519
    t_total: 17300
    cycles: 0.3

vit_large:
  optimizer:
    type: AdamW
    lr: 0.0001
    betas: [0.9, 0.999]
    weight_decay: 0.06
  scheduler:
    type: WarmupCosineSchedule
    warmup_steps: 519
    t_total: 17300
    cycles: 0.3